# This is a basic workflow to help you get started with Actions

name: check latest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sapmachine:
    strategy:
      matrix:
        java-package: [jdk, jre]
        version: [11, 13.0.1]
       
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: Shegox/setup-java@main
        with: 
          distribution: 'sapmachine'
          java-version: ${{ matrix.version }}
          java-package: ${{ matrix.java-package }}
          check-latest: true
      - run: java -version
