# This is a basic workflow to help you get started with Actions

name: Full Test Matrix 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sapmachine:
    strategy:
      matrix:
        java-package: [jdk, jre]
        version: [21, 23-ea, 21.0.2+2-ea, 17, 13.0.1, 13]
        os: [ubuntu-latest, macos-latest, windows-latest]
        container: ['', "alpine:latest"]
        exclude:
        - os: macos-latest
          container: "alpine:latest"
        - os: windows-latest
          container: "alpine:latest"
    runs-on: ${{ matrix.os }}
  # This workflow contains a single job called "build"
    container:
      image: ${{ matrix.container || '' }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: Shegox/setup-java@main
        with: 
          distribution: 'sapmachine' # See 'Supported distributions' for available options
          java-version: ${{ matrix.version }}
          java-package: ${{ matrix.java-package }}
      - run: java -version
